# Generated by Django 3.1 on 2020-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zamena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=('1', '1'))),
                ('letter', models.CharField(choices=[('a', 'a'), ('б', 'б')], default=('a', 'a'), max_length=2)),
                ('predmet', models.CharField(choices=[('Русский язык', 'Русский язык'), ('Математика', 'Математика')], default=('Русский язык', 'Русский язык'), max_length=100)),
            ],
        ),
    ]
