# Generated by Django 3.1 on 2020-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamena',
            name='lesson',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=('1', '1'), max_length=2),
        ),
    ]
