# Generated by Django 3.1 on 2020-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0003_auto_20201016_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamena',
            name='pub_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
