# Generated by Django 3.1 on 2020-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0005_auto_20201018_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamena',
            name='date_pub',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='how_lesson',
            field=models.IntegerField(blank=True, null=True, verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='lesson',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=('5', '5'), max_length=2, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='letter',
            field=models.CharField(choices=[('a', 'a'), ('б', 'б')], default=('a', 'a'), max_length=2, verbose_name='Буква'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='predmet',
            field=models.CharField(choices=[('Английский', 'Английский'), ('Астрономия', 'Астрономия'), ('Биология', 'Биология'), ('Индивидуальный проект', 'Индивидуальный проект'), ('Информатика и ИКТ', 'Информатика и ИКТ'), ('История', 'История'), ('Литература', 'Литература'), ('Математика', 'Математика'), ('Обществознание', 'Обществознание'), ('ОБЖ', 'ОБЖ'), ('Право', 'Право'), ('Родная (татарская) литература', 'Родная (татарская) литература'), ('Родной (татарский) язык', 'Родной (татарский) язык'), ('Русский язык', 'Русский язык'), ('Физика', 'Физика'), ('Физическая культура', 'Физическая культура'), ('Химия', 'Химия')], default=('Английский', 'Английский'), max_length=100, verbose_name='Предмет'),
        ),
    ]
