# Generated by Django 3.1 on 2020-10-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0006_auto_20201020_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamena',
            name='date_pub',
        ),
    ]
