# Generated by Django 3.1 on 2020-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0007_remove_zamena_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamena',
            name='additional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные замены'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='cabinet',
            field=models.IntegerField(null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='how_lesson',
            field=models.IntegerField(null=True, verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='zamena',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('А и Б', 'А и Б')], default=('А', 'А'), max_length=5, verbose_name='Буква'),
        ),
    ]
