# Generated by Django 3.1 on 2020-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0008_auto_20201112_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_zamena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дополнительной замены')),
                ('description', models.CharField(max_length=255, verbose_name='Описание дополнительной замены')),
            ],
        ),
        migrations.RemoveField(
            model_name='zamena',
            name='additional',
        ),
    ]
