# Generated by Django 3.1 on 2021-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0011_additional_zamena_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_zamena',
            name='description',
            field=models.TextField(verbose_name='Описание новости'),
        ),
    ]
