# Generated by Django 3.1 on 2021-01-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnazium', '0015_auto_20210104_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_zamena',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
